### ISSUE TITLE
Event nouveaux messages...

### ISSUE THREAD

**Issue by Giga77** [hacf-fr/hass-ecoledirecte#38]
Faut-il faire un event pour les nouveaux messages ?

**Comment by Dites33** [comment]
Peut être une bonne idée pour nous notifier

**Comment by Giga77** [comment]
Simplification des attributs :
![image](https://github.com/user-attachments/assets/bc798e73-c211-406f-8d6f-d8b405158e96)

Ce qui permet de faire une automatisation :
```
alias: EcoleDirecte - message non lu
description: ""
trigger:
  - platform: state
    entity_id:
      - sensor.ecole_directe_messagerie
    attribute: non lu
condition: []
action:
  - action: notify.notify
    data: {}
mode: single
```
